Update issue templates to add Feature Enhancement
theopenlab/openlab pull request #204
Opened 2019-03-04 08:10 UTC by kiwik

1. Add a new template for feature enhancement for Openlab
2. Add default label for each template

2019-03-04 08:28 UTC, liusheng submitted a review, later dismissed
lgtm

2019-03-04 08:36 UTC, kiwik commented
And I have update OpenLab document website, see here https://docs.openlabtesting.org/publications/contributors/development-guide#working-on-feature-and-bug to add feature related workflow

2019-03-04 13:51 UTC, mrhillsman requested changes
Let's add hogepodge and stmcginnis as assignees for test requests; maybe that will speed them up

2019-03-05 01:34 UTC, huangtianhua submitted a review, later dismissed
lgtm，thanks

2019-03-05 06:14 UTC, kiwik commented
@mrhillsman have added them into reviewer list

2019-03-06 09:15 UTC, kiwik commented
@mrhillsman address your comment

2019-03-06 14:05 UTC, mrhillsman approved these changes

2019-03-06 14:06 UTC, stmcginnis approved these changes
LGTM

2019-03-06 14:06 UTC, stmcginnis commented on .github/ISSUE_TEMPLATE/report-bug.md
> +Thank you for reporting bug!
"reporting a bug" or "reporting this bug" would be more grammatically correct, but I don't think it's a big deal.

2019-03-06 14:06 UTC, merged